// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || '';

// Check if Supabase is configured
export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const createSupabaseClient = (): SupabaseClient<Database> => {
  if (!isSupabaseConfigured) {
    // Return a placeholder client that won't crash but won't work either
    // This allows the app to load while showing appropriate "not configured" states
    return createClient<Database>(
      'https://placeholder.supabase.co',
      'placeholder-key-for-type-safety'
    );
  }
  
  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      // Disable error logging in production
      fetch: (url, options = {}) => {
        return fetch(url, {
          ...options,
          // Add error handling wrapper
        }).catch(error => {
          // Log sanitized error in development only
          if (process.env.NODE_ENV === 'development') {
            console.error('Supabase request failed:', error.message);
          }
          throw error;
        });
      }
    }
  });
};

export const supabase = createSupabaseClient();
